#!/usr/bin/env python
# EASY-INSTALL-ENTRY-SCRIPT: 'nose==0.9.2','console_scripts','nosetests'
__requires__ = 'nose==0.9.2'
import sys
from pkg_resources import load_entry_point

sys.argv[1:] = ['--with-doctest']

sys.exit(
   load_entry_point('nose==0.9.2', 'console_scripts', 'nosetests')()
)
